# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c2c6c269db8d3a005bfcb36c830968d87e569cfb4ca491343c89eb77862392f2b45ef29da1fdcde01306aa8765bae6742508c699f912a8514f068c5789ca0a

test:
  secret_key_base: 3ab80a22f3ff5e8c4063eff102955c530a123d6fcf529f422dd1bd6a72d5d49c8f0e1c44c88078038b6b7e7e94c08654af7ce61f0b0c49e68bbdb205b30a2c65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
